# Generated by Django 5.0.13 on 2025-04-27 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 27, 8, 35, 37, 626663)
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="date_last_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 27, 8, 35, 37, 626663)
            ),
        ),
    ]
