version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ems
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # utilitar baza de date mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ems
      - DB_USER=root
      - DB_PASSWORD=root

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - backend


volumes:
  db_data:
