global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-swarm'
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'tasks.agent'    # Portainer agent runs on 9323 with metrics-addr
        type: A
        port: 9323

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend:4000'] 

  - job_name: 'teams-service'
    static_configs:
      - targets: ['teams_module:8005']
      
  - job_name: 'tasks-service'
    static_configs:
      - targets: ['tasks_module:8004']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: A
        port: 8080