name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build and push frontend
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: anacicoare/frontend-image:latest

    # Build and push business module
    - name: Build and push business module
      uses: docker/build-push-action@v4
      with:
        context: ./business_module
        push: true
        tags: anacicoare/business-module-image:latest

    # Build and push payments module
    - name: Build and push payments module
      uses: docker/build-push-action@v4
      with:
        context: ./payments_module
        push: true
        tags: anacicoare/payments-module-image:latest

    # Build and push tasks module
    - name: Build and push tasks module
      uses: docker/build-push-action@v4
      with:
        context: ./tasks_module
        push: true
        tags: anacicoare/tasks-module-image:latest

    # Build and push teams module
    - name: Build and push teams module
      uses: docker/build-push-action@v4
      with:
        context: ./teams_module
        push: true
        tags: anacicoare/teams-module-image:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Add deployment steps here based on your deployment strategy
    # For example, if deploying to a server:
    - name: Deploy to server
      run: |
        echo "Add your deployment commands here"
        # Example: ssh into your server and pull new images
        # ssh user@your-server "docker-compose pull && docker-compose up -d"
